const mockDB = {
  users: [
    {
      userId: 101,
      seqn: 100001,
      birthDate: "1996-06-15",
      sex: "F",
      raceEthnicity: "Non-Hispanic White",
    },
    {
      userId: 102,
      seqn: 100002,
      birthDate: "1980-02-25",
      sex: "M",
      raceEthnicity: "Non-Hispanic White",
    },
    {
      userId: 103,
      seqn: 100003,
      birthDate: "1987-11-05",
      sex: "F",
      raceEthnicity: "Hispanic",
    },
  ],
  biomarkers: [
    {
      biomarkerId: 1,
      name: "Albumin",
      units: "g/dL",
      description: "Serum albumin",
      nhanesVarCode: "LBXSAL",
    },
    {
      biomarkerId: 2,
      name: "Alkaline phosphatase",
      units: "U/L",
      description: "ALP enzyme level",
      nhanesVarCode: "LBXSAPSI",
    },
    {
      biomarkerId: 3,
      name: "Creatinine",
      units: "mg/dL",
      description: "Serum creatinine",
      nhanesVarCode: "LBXSCR",
    },
    {
      biomarkerId: 4,
      name: "Fasting glucose",
      units: "mg/dL",
      description: "Fasting glucose",
      nhanesVarCode: "LBXGLU",
    },
    {
      biomarkerId: 5,
      name: "High-sens. CRP",
      units: "mg/L",
      description: "High-sensitivity C-Reactive Protein",
      nhanesVarCode: "LBXHSCRP",
    },
    {
      biomarkerId: 6,
      name: "White-blood-cell count",
      units: "10³ cells/µL",
      description: "White blood cell count",
      nhanesVarCode: "LBXWBCSI",
    },
    {
      biomarkerId: 7,
      name: "Lymphocyte",
      units: "%",
      description: "Lymphocyte percentage",
      nhanesVarCode: "LBXLYPCT",
    },
    {
      biomarkerId: 8,
      name: "Mean corpuscular volume",
      units: "fL",
      description: "Mean corpuscular volume",
      nhanesVarCode: "LBXMCVSI",
    },
    {
      biomarkerId: 9,
      name: "Red-cell distribution width",
      units: "%",
      description: "Red cell distribution width",
      nhanesVarCode: "LBXRDW",
    },
  ],
  profiles: {
    101: {
      biomarkers: [
        {
          biomarkerId: 1,
          name: "Albumin",
          units: "g/dL",
          value: 4.2,
          takenAt: "2025-05-01",
        },
        {
          biomarkerId: 2,
          name: "Alkaline phosphatase",
          units: "U/L",
          value: 65,
          takenAt: "2025-05-01",
        },
        {
          biomarkerId: 3,
          name: "Creatinine",
          units: "mg/dL",
          value: 1.0,
          takenAt: "2025-05-01",
        },
        {
          biomarkerId: 4,
          name: "Fasting glucose",
          units: "mg/dL",
          value: 85,
          takenAt: "2025-05-01",
        },
        {
          biomarkerId: 5,
          name: "High-sens. CRP",
          units: "mg/L",
          value: 1.2,
          takenAt: "2025-05-01",
        },
        {
          biomarkerId: 6,
          name: "White-blood-cell count",
          units: "10³ cells/µL",
          value: 6.0,
          takenAt: "2025-05-01",
        },
        {
          biomarkerId: 7,
          name: "Lymphocyte",
          units: "%",
          value: 30,
          takenAt: "2025-05-01",
        },
        {
          biomarkerId: 8,
          name: "Mean corpuscular volume",
          units: "fL",
          value: 90,
          takenAt: "2025-05-01",
        },
        {
          biomarkerId: 9,
          name: "Red-cell distribution width",
          units: "%",
          value: 12.5,
          takenAt: "2025-05-01",
        },
      ],
    },
    102: {
      biomarkers: [
        {
          biomarkerId: 1,
          name: "Albumin",
          units: "g/dL",
          value: 3.8,
          takenAt: "2025-04-10",
        },
        {
          biomarkerId: 2,
          name: "Alkaline phosphatase",
          units: "U/L",
          value: 95,
          takenAt: "2025-04-10",
        },
        {
          biomarkerId: 3,
          name: "Creatinine",
          units: "mg/dL",
          value: 1.4,
          takenAt: "2025-04-10",
        },
        {
          biomarkerId: 4,
          name: "Fasting glucose",
          units: "mg/dL",
          value: 105,
          takenAt: "2025-04-10",
        },
        {
          biomarkerId: 5,
          name: "High-sens. CRP",
          units: "mg/L",
          value: 3.1,
          takenAt: "2025-04-10",
        },
        {
          biomarkerId: 6,
          name: "White-blood-cell count",
          units: "10³ cells/µL",
          value: 8.2,
          takenAt: "2025-04-10",
        },
        {
          biomarkerId: 7,
          name: "Lymphocyte",
          units: "%",
          value: 20,
          takenAt: "2025-04-10",
        },
        {
          biomarkerId: 8,
          name: "Mean corpuscular volume",
          units: "fL",
          value: 100,
          takenAt: "2025-04-10",
        },
        {
          biomarkerId: 9,
          name: "Red-cell distribution width",
          units: "%",
          value: 14.0,
          takenAt: "2025-04-10",
        },
      ],
    },
    103: {
      biomarkers: [
        {
          biomarkerId: 1,
          name: "Albumin",
          units: "g/dL",
          value: 4.0,
          takenAt: "2025-05-10",
        },
        {
          biomarkerId: 2,
          name: "Alkaline phosphatase",
          units: "U/L",
          value: 80,
          takenAt: "2025-05-10",
        },
        {
          biomarkerId: 3,
          name: "Creatinine",
          units: "mg/dL",
          value: 1.1,
          takenAt: "2025-05-10",
        },
        {
          biomarkerId: 4,
          name: "Fasting glucose",
          units: "mg/dL",
          value: 90,
          takenAt: "2025-05-10",
        },
        {
          biomarkerId: 5,
          name: "High-sens. CRP",
          units: "mg/L",
          value: 2.5,
          takenAt: "2025-05-10",
        },
        {
          biomarkerId: 6,
          name: "White-blood-cell count",
          units: "10³ cells/µL",
          value: 7.0,
          takenAt: "2025-05-10",
        },
        {
          biomarkerId: 7,
          name: "Lymphocyte",
          units: "%",
          value: 25,
          takenAt: "2025-05-10",
        },
        {
          biomarkerId: 8,
          name: "Mean corpuscular volume",
          units: "fL",
          value: 92,
          takenAt: "2025-05-10",
        },
        {
          biomarkerId: 9,
          name: "Red-cell distribution width",
          units: "%",
          value: 13.0,
          takenAt: "2025-05-10",
        },
      ],
    },
  },
  bioAges: {
    101: [
      {
        modelName: "Phenotypic Age",
        bioAgeYears: 24.2,
        ageGap: -4.8,
        computedAt: "2025-05-10T12:00:00Z",
      },
    ],
    102: [
      {
        modelName: "Phenotypic Age",
        bioAgeYears: 52.1,
        ageGap: 7.1,
        computedAt: "2025-04-10T12:00:00Z",
      },
    ],
    103: [
      {
        modelName: "Phenotypic Age",
        bioAgeYears: 41.3,
        ageGap: 3.3,
        computedAt: "2024-05-10T09:00:00Z",
      },
      {
        modelName: "Phenotypic Age",
        bioAgeYears: 38.7,
        ageGap: 0.0,
        computedAt: "2024-11-10T09:00:00Z",
      },
      {
        modelName: "Phenotypic Age",
        bioAgeYears: 35.2,
        ageGap: -3.0,
        computedAt: "2025-05-10T09:00:00Z",
      },
    ],
  },
  sessions: {
    201: {
      userId: 101,
      sessionDate: "2025-05-15",
      fastingStatus: true,
      measurements: [],
    },
    202: {
      userId: 101,
      sessionDate: "2025-04-01",
      fastingStatus: false,
      measurements: [],
    },
    203: {
      userId: 101,
      sessionDate: "2025-02-01",
      fastingStatus: true,
      measurements: [],
    },
    301: {
      userId: 102,
      sessionDate: "2025-04-10",
      fastingStatus: false,
      measurements: [],
    },
    302: {
      userId: 102,
      sessionDate: "2024-10-10",
      fastingStatus: true,
      measurements: [],
    },
    303: {
      userId: 102,
      sessionDate: "2024-04-10",
      fastingStatus: false,
      measurements: [],
    },
    401: {
      userId: 103,
      sessionDate: "2025-05-10",
      fastingStatus: false,
      measurements: [],
    },
    402: {
      userId: 103,
      sessionDate: "2024-11-10",
      fastingStatus: true,
      measurements: [],
    },
    403: {
      userId: 103,
      sessionDate: "2024-05-10",
      fastingStatus: false,
      measurements: [],
    },
  },
  ranges: {
    /* demo reference ranges */
  },
};
